preconnect:
  - https://gcore.jsdelivr.net
  - https://unpkg.com
  - https://cdn.bootcdn.net

inject:
  head:
    # - <link rel="apple-touch-icon" sizes="180x180" href="/assets/xaoxuu/favicon/apple-touch-icon.png">
    # - <link rel="icon" type="image/png" sizes="32x32" href="/assets/xaoxuu/favicon/favicon-32x32.png">
    # - <link rel="icon" type="image/png" sizes="16x16" href="/assets/xaoxuu/favicon/favicon-16x16.png">
    # - <link rel="manifest" href="/assets/xaoxuu/favicon/site.webmanifest">
    # - <link rel="shortcut icon" href="/assets/xaoxuu/favicon/favicon.ico">
    - <meta name="theme-color" content="#f8f8f8">
    - <link rel="stylesheet" href="https://cdn.bootcdn.net/ajax/libs/lxgw-wenkai-screen-webfont/1.7.0/style.min.css" media="all" />

logo:
  icon: https://dagongdeyatou-img-bed.oss-cn-hangzhou.aliyuncs.com/img/2026/01/shiba-20260117-095821.png
  title: 打工的丫头
  subtitle: "年少藏山河于心 以为过目即永 | 如今信寸墨留痕 方抵岁月无声"
menubar:
  items:
    - id: post
      theme: "#1BCDFC"
      icon: solar:documents-bold-duotone
      title: 博客
      url: /
    - id: note
      theme: "#3DC550"
      icon: solar:notebook-bookmark-bold-duotone
      title: 笔记
      url: /note/
    - id: about
      theme: "#FA6400"
      icon: solar:planet-bold-duotone
      title: 关于
      url: /about/
    - id: friends
      theme: "#F44336"
      icon: solar:chat-square-like-bold-duotone
      title: 社交
      url: /friends/

site_tree:
  home:
    sidebar: starter, welcome, recent
  index_blog:
    sidebar: starter, welcome, recent
  index_topic:
    menu_id: topic
  topic:
    menu_id: topic

article:
  type: tech # 若要使用图文类文章，改成story
  auto_excerpt: 50 # 设置自动摘要长度
  license: "本文由[@打工的丫头](/)编写，采用 [署名-非商业性使用-相同方式共享 4.0 国际](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处，带带单打独斗的弟弟。" # 许可协议
  related_posts: #开启可能感兴趣文章
    enable: true
    title: 您可能感兴趣的文章
  share: [wechat, weibo, email, link]

style:
  prefers_theme: light # light, dark, auto
  text-align: justify
  smooth_scroll: false
  codeblock:
    scrollbar: 0px
  font-size:
    body: 1rem
  font-family:
    logo: '"LXGW WenKai Screen", system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    body: '"LXGW WenKai Screen", system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    code: '"LXGW WenKai Screen", Menlo, Monaco, Consolas, system-ui, "Courier New", monospace, sans-serif'
    codeblock: 'Menlo, Monaco, Consolas, system-ui, "Courier New", monospace, sans-serif'

# 文章搜索
search:
  service: local_search # local_search, todo...
  local_search:
    field: all # post, page, all
    path: /search.json # 搜索文件存放位置
    content: true # 是否搜索内容
    skip_search: [] # 指定 path 中的内容不被搜索。
    codeblock: true # 是否搜索代码块（需要content: true)

footer:
  social:
    # github:
    #   icon: '<img src="https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.12/social/08a41b181ce68.svg"/>'
    #   url: /
    # music:
    #   icon: '<img src="https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.12/social/3845874.svg"/>'
    #   url: /
    # unsplash:
    #   icon: '<img src="https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.12/social/3616429.svg"/>'
    #   url: /
    # comments:
    #   icon: '<img src="https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.12/social/942ebbf1a4b91.svg"/>'
    #   url: /about/#comments
  sitemap:
    # - title: 博客
    #   items:
    #     - '[近期发布](/)'
    #     - '[分类](/blog/categories/)'
    #     - '[标签](/blog/tags/)'
    #     - '[归档](/blog/archives/)'
    # - title: 项目
    #   items:
    #     - '[xxx](/)'
    #     - '[xxx](/)'
    #     - '[xxx](/)'
    #     - '[xxx](/)'
    # - title: 社交
    #   items:
    #     - '[xxx](/)'
    #     - '[xxx](/)'
    #     - '[xxx](/)'
    #     - '[xxx](/)'
    # - title: 关于
    #   items:
    #     - '[xxx](/)'
    #     - '[xxx](/)'
    #     - '[xxx](/)'
    #     - '[xxx](/)'
  content: | # 支持 Markdown 格式
    本站由 [@打工的丫头](/) 使用 [{theme.name} {theme.version}]({theme.tree}) 主题创建。
    本博客所有文章除特别声明外，均采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处，带带单打独斗的弟弟。
  # 主题用户越多，开发者维护和更新的积极性就越高，如果您喜欢本主题，请在适当的位置显示主题信息和仓库链接以表支持。

######## Comments ########
comments:
  service: twikoo # beaudar, utterances, giscus, twikoo, waline, artalk
  comment_title: 如果有疑问的话，欢迎留言讨论~
  lazyload: false # true / false
  custom_css: twikoo # artalk,twikoo,... 可以为没有全局启用的评论加载自定义样式
  # Twikoo
  # https://twikoo.js.org/
  twikoo:
    js: https://gcore.jsdelivr.net/npm/twikoo@1.6/dist/twikoo.all.min.js # 建议锁定版本
    envId: https://twikoo.dagongdeyatou.cn # vercel函数
